apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.argoNamespace }}
spec:
  project: {{ .Values.projectName }}
  source:
    directory:
      recurse: true
    repoURL: "{{ .Values.github.repo }}"
    targetRevision: HEAD
    path: ./
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace | squote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
