apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.argoNamespace }}
  name: core-gitops-repo
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  project: {{ .Values.projectName | b64enc }}
  type: {{ "git" | b64enc }}
  url: {{ .Values.github.repo | b64enc }}
  username: {{ .Values.github.org | b64enc }}
  password: {{ .Values.github.token | b64enc }}
